### ISSUE TITLE
Missing `test_ioproblem.jl`

### ISSUE THREAD

**Issue by ReubenJ** [Herb-AI/HerbSpecification.jl#5]
Test(s) currently fails because the file `test/test_ioproblem.jl` is missing.

**Comment by nicolaefilat** [comment]
I think @THinnerichs solved this issue here https://github.com/Herb-AI/HerbSpecification.jl/commit/132f28253711b14301cc961812d290dd6ae6ef10

**Comment by THinnerichs** [comment]
I will mark this as resolved, as tests seem to pass? Please re-open, when this still occurs.
